name: mobuyg02
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  #flutter: uses-material-design: true,

   #To add assets to your application, add an assets section, like this:
   assets:
    - assets/icons/yasun.jpg
    - assets/icons/meyve_yet.jpeg
    - assets/icons/sebze_yet.jpeg
    - assets/icons/peyzaj.jpeg
    - assets/icons/yildiz.png
    - assets/icons/kasimpati.png
    - assets/icons/gül.png
    - assets/icons/lale.png
    - assets/icons/zambak.png
    - assets/icons/nergis.png
    - assets/icons/papatya.png
    - assets/icons/sümbül.png
    - assets/icons/menekse.png
    - assets/icons/karanfil.png
    - assets/icons/orkide.png
    - assets/icons/yasemin.png
    - assets/icons/lavanta.png
    - assets/icons/şakayık.png
    - assets/icons/elma.png
    - assets/icons/armüt.png
    - assets/icons/zeytin.png
    - assets/icons/trabzonhürmasi.png
    - assets/icons/hürma.png
    - assets/icons/yenidünya.png
    - assets/icons/müz.png
    - assets/icons/incir.png
    - assets/icons/muşmula.png
    - assets/icons/ayva.png
    - assets/icons/aliç.png
    - assets/icons/küşbürnü.png
    - assets/icons/uvez.jpeg
    - assets/icons/visne.png
    - assets/icons/kiraz.png
    - assets/icons/kayisi.png
    - assets/icons/igde.png
    - assets/icons/kizilcik.png
    - assets/icons/seftali.png
    - assets/icons/erik.png
    - assets/icons/ceviz.png
    - assets/icons/fistik.png
    - assets/icons/findik.png
    - assets/icons/badem.png
    - assets/icons/kestane.png
    - assets/icons/ahududu.png
    - assets/icons/incir.png
    - assets/icons/dut.png
    - assets/icons/bogurtlen.png
    - assets/icons/cilek.png
    - assets/icons/üzüm.png
    - assets/icons/kahve.png
    - assets/icons/kakao.png
    - assets/icons/cay.png
    - assets/icons/brokoli.png
    - assets/icons/karnabahar.png
    - assets/icons/havuc.png
    - assets/icons/brüklahana.png
    - assets/icons/baslahana.png
    - assets/icons/pirasa.png
    - assets/icons/ispanak.png
    - assets/icons/marul.png
    - assets/icons/biber.png
    - assets/icons/tazefasulye.png
    - assets/icons/domates.png
    - assets/icons/enginar.png
    - assets/icons/kabak.png
    - assets/icons/kavun.png
    - assets/icons/karpuz.png
    - assets/icons/bezelye.png
    - assets/icons/hıyar.png
    - assets/icons/turşhıyar.png
    - assets/icons/frezya.png
    - assets/icons/begonya.png
    - assets/icons/saksıkak.png


  #  - images/a_dot_ham.jpeg

   #An image asset can refer to one or more resolution-specific "variants", see
   #https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
   #fonts:
   # - family: Schyler
   #   fonts:
   #    - asset: fonts/Schyler-Regular.ttf
   #    - asset: fonts/Schyler-Italic.ttf
   #       style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
